# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "sr_mod"
    "nvidia"
    "nvidia_drm"
    "nvidia_uvm"
    "nvidia_modeset"
    "nvidiafb"
  ];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/8f29f7cf-0bea-45a9-945c-9c35e9ac41da";
      fsType = "btrfs";
      options = [
        "subvol=@nix"
        "noatime"
        "compress-force=zstd:4"
        "ssd"
        "discard=async"
      ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/14A5-3735";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };
  };

  zramSwap = {
    enable = true;
    memoryPercent = 12;
  };

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = false;
  };

  hardware.enableRedistributableFirmware = true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
