#[Settings]

screenshot-sw=yes
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=4

#osd-level=2
#save-position-on-quit

geometry=50%:50%
keep-open
osd-fractions
use-filedir-conf
#border=no

hdr-compute-peak=no
vo=gpu
hwdec=nvdec

#profile=LQ
profile=HQ


[HQ]
scale=ewa_lanczos
dscale=ewa_lanczos
sigmoid-upscaling

deband=yes
deband-iterations=2
deband-threshold=64
deband-range=48

[LQ]
scale=bilinear
dscale=bilinear

deband=yes
deband-iterations=4
deband-threshold=64
deband-range=24